version: 3
networks:
  expense:
volumes:
  mysql:
Services:
  mysql:
    image: sankarjuvva/mysql.v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  backend:
    image: sankarjuvva/backend.v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
    - mysql
  frontend:
    image: sankarjuvva/frontend.v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend