version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: sankarjuvva/mysql:latest
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  backend:
    image: sankarjuvva/backend:latest
    container_name: backend
    command: sh -c "sleep 10 && node /opt/server/index.js"
    depend_on:
    - mysql
  frontend:
    image: sankarjuvva/frontend:latest
    container_name: frontend
    ports:
    - 80:80
    depend_on:
    - backend